{
 "title": "Kubernetes All Nodes",
 "description": "Dashboard to get an overview of all nodes in a Kubernetes Cluster",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory chache per node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n node_memory_Cached\n\n)\n * on(instance) group_left(nodename)\n(\n node_uname_info \n)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Slab Unreclaimable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\nnode_memory_SUnreclaim\n)\n* on (instance) group_right(nodemame)\n(\nnode_uname_info\n)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IO \"EventStore\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  rate(node_disk_bytes_read{device=\"sdh\"}[5m])\n) \n* on(instance) group_left(nodename) \n(\n  node_uname_info{nodename=~\"fraudapp[4-6].*\"}\n)",
     "legendFormat": "READ bytes {{nodename}}"
    },
    {
     "expr": "(\n  rate(node_disk_bytes_written{device=\"sdh\"}[5m])\n) \n* on(instance) group_left(nodename) \n(\n  node_uname_info{nodename=~\"fraudapp[4-6].*\"}\n)",
     "legendFormat": "WRITE bytes {{nodename}}"
    },
    {
     "expr": "(\n  sum(delta(node_disk_io_time_ms{device=\"sdh\"}[5m]))  by (instance) \n  /\n  (\n    sum(delta(node_cpu{mode=\"iowait\"}[5m])) by (instance) +\n    sum(delta(node_cpu{mode=\"idle\"}[5m])) by (instance) +\n    sum(delta(node_cpu{mode=\"user\"}[5m])) by (instance) +\n    sum(delta(node_cpu{mode=\"system\"}[5m])) by (instance) \n  ) \n  / 4\n)\n* on(instance) group_left(nodename)\n(\n  node_uname_info{nodename=~\"fraudapp[4-6].*\"}\n)",
     "legendFormat": "IO Utilization {{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IO \"Projections\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  rate(node_disk_bytes_read{device=\"sdf\"}[5m])\n) \n* on(instance) group_left(nodename) \n(\n  node_uname_info{nodename=~\"fraudapp[4-6].*\"}\n)",
     "legendFormat": "READ bytes {{nodename}}"
    },
    {
     "expr": "(\n  rate(node_disk_bytes_written{device=\"sdf\"}[5m])\n) \n* on(instance) group_left(nodename) \n(\n  node_uname_info{nodename=~\"fraudapp[4-6].*\"}\n)",
     "legendFormat": "WRITE bytes {{nodename}}"
    },
    {
     "expr": "(\n  sum(delta(node_disk_io_time_ms{device=\"sdf\"}[5m]))  by (instance) \n  /\n  (\n    sum(delta(node_cpu{mode=\"iowait\"}[5m])) by (instance) +\n    sum(delta(node_cpu{mode=\"idle\"}[5m])) by (instance) +\n    sum(delta(node_cpu{mode=\"user\"}[5m])) by (instance) +\n    sum(delta(node_cpu{mode=\"system\"}[5m])) by (instance) \n  ) \n  / 4\n)\n* on(instance) group_left(nodename)\n(\n  node_uname_info{nodename=~\"fraudapp[4-6].*\"}\n)",
     "legendFormat": "IO Utilization {{nodename}}"
    }
   ]
  },
  {
   "title": "Idle cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{mode=\"idle\"}[2m])) * 100"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal)) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_ms[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  }
 ]
}